import Header from "./components/Header";

export const metadata = {
  title: "Travel",
  description: "Generated by create next app",
};

export default function MarketplaceLayout({ children }) {
  return (
    <section className="overflow-auto w-screen">
      <Header />
      {children}
    </section>
  );
}
