export const metadata = {
  title: "Travel",
  description: "Generated by create next app",
};

export default function MarketplaceLayout({ children }) {
  return <section className="overflow-auto w-screen">{children}</section>;
}
